#!/bin/bash

set -x

qat_server_url=root@192.168.1.126
project_root_at_remote=/root/bench-dpdk-pdump-qat

function build
{
    ssh ${qat_server_url} "mkdir -p ${project_root_at_remote}" && \
        scp main.c Makefile ${qat_server_url}:${project_root_at_remote} && \
        ssh ${qat_server_url} "cd ${project_root_at_remote} && RTE_SDK=/root/DPDK/dpdk-stable-17.11.1 RTE_TARGET=build make"
}

function run
{
    ssh ${qat_server_url} "cd ${project_root_at_remote} && make run"
}

case $1 in
    build)
        build
        ;;
    run)
        run
        ;;
    *)
        echo "Usage: $0 {build|run}"
        exit 1
esac
