#!/bin/bash

set -x

qat=root@192.168.1.126
remote_project_root=/root/bench-dpdk-pdump-qat
remote_dpdk_root=/root/DPDK/dpdk-stable-17.11.1-origin
remote_icp_root=/root/QAT1.7
remote_qatzip_root=/root/QATzip
remote_l3fwd_dir=${remote_dpdk_root}/examples/l3fwd
remote_l3fwd_bin=${remote_l3fwd_dir}/build/l3fwd
remote_pdump_qat=${remote_project_root}/dpdk-pdump-qat
remote_env_vars="RTE_SDK=${remote_dpdk_root} RTE_TARGET=build ICP_ROOT=${remote_icp_root} QATZIP_ROOT=${remote_qatzip_root}"

function build
{
    ssh $qat "mkdir -p ${remote_project_root}" && \
        scp main.c Makefile $qat:${remote_project_root} && \
        ssh $qat "make -C ${remote_project_root} ${remote_env_vars}"

    ssh $qat "test -f ${remote_l3fwd_bin} ||
        make -C ${remote_l3fwd_dir} ${remote_env_vars}"
}

function run_test
{
    ssh $qat "timeout 16 ${remote_l3fwd_bin} -l 1,2 -n 4 -- -p 0x3 --config=\"(0,0,1),(1,0,2)\""
}

function setup_dpdk
{
    ssh $qat "modprobe uio && cd ${remote_dpdk_root} && 
        (insmod ./build/kmod/igb_uio.ko || true) &&
        ./usertools/dpdk-devbind.py -b igb_uio 03:00.0 03:00.1"
    ssh $qat "mkdir -p /mnt/huge && (umount /mnt/huge || true) && 
        mount -t hugetlbfs nodev /mnt/huge && 
        echo 256 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages"
}

function restart_nginx
{
    scp nginx.conf $qat:/etc/nginx/ && ssh $qat "systemctl restart nginx"
}

function restart_qat_service
{
    scp dh895xcc_dev0.conf $qat:/etc/ && ssh $qat "service qat_service restart"
}

function benchmark
{
    local bench_id=$1
    scp bench $qat:${remote_project_root}/ && \
        ssh $qat "cd ${remote_project_root} && bash bench ${bench_id}"
}

case $1 in
    build)
        build
        ;;
    test)
        run_test
        ;;
    dpdk)
        setup_dpdk
        ;;
    nginx)
        restart_nginx
        ;;
    qat)
        restart_qat_service
        ;;
    bench)
        benchmark $2
        ;;
    *)
        echo "Usage: $0 {build|test|dpdk}"
        exit 1
esac
