#!/bin/bash

set -euo pipefail

REMOTE_PROJECT_ROOT=/root/workspace/bench-dpdk-pdump-qat
REMOTE_DPDK_ROOT=/root/DPDK/dpdk-18.05
REMOTE_ICP_ROOT=/root/QAT
REMOTE_QATZIP_ROOT=/root/QATzip
REMOTE_L3FWD_DIR=${REMOTE_DPDK_ROOT}/examples/l3fwd
REMOTE_L3FWD_BIN=${REMOTE_L3FWD_DIR}/build/l3fwd
REMOTE_PDUMP_QAT=${REMOTE_PROJECT_ROOT}/dpdk-pdump-qat
REMOTE_ENV_VARS="RTE_SDK=${REMOTE_DPDK_ROOT} RTE_TARGET=build ICP_ROOT=${REMOTE_ICP_ROOT} QATZIP_ROOT=${REMOTE_QATZIP_ROOT}"

function print_usage
{
    echo "Usage: $0 <host> <command> [path_to_script] ['script_args']"
}

qat_server=${1:-}
cmd=${2:-}
script_to_run=${3:-}
script_args=${4:-}

echo "Do execute cmd: $0 ${qat_server} ${cmd} ${script_to_run} ${script_args}"

if [[ -z "${qat_server}" ]] || [[ -z "${cmd}" ]]; then
    print_usage
    exit 1
fi

function init_project
{
    ssh ${qat_server} "mkdir -p ${REMOTE_PROJECT_ROOT}"
}

function run_script
{
    local script_to_run="$1"
    local script_args="${2:-}"

    scp ${script_to_run} ${qat_server}:${REMOTE_PROJECT_ROOT}/ && \
        ssh ${qat_server} "cd ${REMOTE_PROJECT_ROOT} && bash ${script_to_run} ${script_args}"
}

case $cmd in
    init)
        init_project
        ;;
    run)
        run_script ${script_to_run} ${script_args}
        ;;
    *)
        print_usage
        exit 1
esac

exit 0
